#!/usr/bin/env bash
#ddev-generated

set -e

if [ "${GOARCH}" = "amd64" ]; then
  ARCH="x86_64";
  BUILD="";
elif [ "${GOARCH}" = "arm64" ]; then
  ARCH="aarch64";
  BUILD="aarch64";
else
  echo "This package does not work on this machines";
  exit 1;
fi

PACKAGE_URL="https://sfc-repo.snowflakecomputing.com/odbc/linux$BUILD/3.3.0/snowflake-odbc-3.3.0.$ARCH.deb"
PACKAGE_NAME="./web-build/snowflake-odbc/snowflake.deb"

rm -f "${PACKAGE_NAME}"

if command -v wget &> /dev/null; then
  wget -O "${PACKAGE_NAME}" "${PACKAGE_URL}"
elif command -v curl &> /dev/null; then
  curl "${PACKAGE_URL}" -o "${PACKAGE_NAME}"
else
  echo "None of the required downloaders (wget, curl) are available."
  exit 1
fi

exit 0;
