#!/usr/bin/env bash
# ddev-generated

set -e

PACKAGE_PATH="./snowflake-odbc"
TMP_PATH="/tmp"
PACKAGE_NAME="snowflake.deb"

echo "Install Snowflake ODBC";

if [ ! -e "./web-build/snowflake-odbc/${PACKAGE_NAME}" ]; then
  echo "Package wasn't correctly downloaded.";
  exit 1;
fi

if [ "${GOARCH}" = "amd64" ]; then
  ARCH="x86_64";
elif [ "${GOARCH}" = "arm64" ]; then
  ARCH="aarch64";
else
  echo "This package does not work on this machines";
  exit 1;
fi

cat <<EOF >> "./web-build/Dockerfile"
# BEGIN Snowflake ODBC Install
RUN (apt-get -qq update || true) && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php${DDEV_PHP_VERSION}-odbc libodbc1 unixodbc
RUN ln -s "/usr/lib/${ARCH}-linux-gnu/libodbccr.so.2" "/etc/libodbccr.so"
ADD "${PACKAGE_PATH}/${PACKAGE_NAME}" "${TMP_PATH}"
RUN dpkg -i "${TMP_PATH}/${PACKAGE_NAME}"
EOF
